#!/usr/bin/env zsh

dir="$(dirname ${0})"
dot_rel="${dir}"/..
dot_abs="$(realpath ${dot_rel})"

# prepare stow to ignore *.zsh files
ln -fs "${dot_abs}"/.stow-global-ignore "${HOME}"

# let stow create the symlinks
pushd "${dot_rel}" >/dev/null
stow *(/)
popd >/dev/null
