#!/usr/bin/env zsh

DIR="$(dirname $0)"
DOTDIR_REL="${DIR}"/..
DOTDIR_ABS="$(realpath ${DOTDIR_REL})"

# jump to parent dir of .dotfiles
pushd "${DOTDIR_REL}"/.. >/dev/null 2>&1
# prepare stow to ignore *.zsh files
ln -fs "${DOTDIR_ABS}"/.stow-global-ignore "${HOME}"
popd >/dev/null 2>&1
# let stow create the symlinks
stow *(/) -t "${HOME}"
